import = [
	"~/dotfiles/alacritty/.config/alacritty/catppuccin-frappe.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 15
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
italic = { family = "JetBrainsMono Nerd Font", style = "Medium Italic" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[window]
title = "Be brave and believe in yourself."
dynamic_title = false
blur = false
opacity = 1

[selection]
save_to_clipboard = true
