import = [
	"~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
italic = { family = "JetBrainsMono Nerd Font", style = "Medium Italic" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[window]
title = "Be brave and believe in yourself."
dynamic_title = false
blur = true
opacity = 0.92

[selection]
save_to_clipboard = true
