alias lf="eza -la --icons"
alias ls="eza"
alias task=~/.local/bin/task
alias python="/opt/homebrew/bin/python3"
alias lg=lazygit
alias nv=nvim
alias dm=dark-mode
alias mv="mv -i"
alias rm="rm -i"
alias cp="cp -i"
alias cls="clear"
alias cldd="sudo rm -rf ~/Library/Developer/Xcode/DerivedData"
alias bat="bat"
