# some copy-paste settings for macos
setw -g mode-keys vi
set -g set-clipboard off
bind-key -T copy-mode-vi v send-keys -X begin-selection
# bind y key in copy mode to select and copy to system clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# other settings

set-option -g status-position top
set-option -g allow-rename off
set -g default-terminal "xterm-256color"
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'
set -g renumber-windows on

set -g prefix C-a

bind s choose-tree -sZ -O name

set -g base-index 1
setw -g pane-base-index 1

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

unbind -T copy-mode-vi MouseDragEnd1Pane

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect' 
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'xamut/tmux-weather'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Tmux weather options
set -g @tmux-weather-format "%C+%t"

# Catppuchin options
set -g @catppuccin_flavour "frappe"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_current_text " #W"
set -ogq @catppuccin_window_text " #W"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_date_time_text " %d-%m %H:%M"

run ~/.tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_weather}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
